"""Double Helix State representations.

Defines the shared state between Strand Alpha (Synthesis Helix) and Strand Beta (Empirical Helix)
and the four ascending elevation tiers.
"""

from typing import Literal, Dict, Any, Optional
from typing_extensions import TypedDict
from pydantic import BaseModel, Field

TierType = Literal[
    "LEVEL_1_KERNEL",
    "LEVEL_2_ECS",
    "LEVEL_3_RENDER",
    "LEVEL_4_PLAYTEST",
    "CONVERGED"
]

ASCENDING_TIERS = [
    "LEVEL_1_KERNEL",
    "LEVEL_2_ECS",
    "LEVEL_3_RENDER",
    "LEVEL_4_PLAYTEST",
    "CONVERGED"
]


class HelixState(TypedDict):
    """Core state dictionary shared across the upward slice loop as specified in the Double Helix specification."""
    tier: TierType
    codebase: Dict[str, str]
    # Telemetry from Strand Beta
    avg_frame_time_ms: float
    allocations_in_loop: int
    headless_bot_crashes: int
    visual_anomalies: int
    # Cognitive Traces from Strand Alpha
    spatial_invariants_valid: bool
    current_cycle: int
    max_cycles_per_tier: int


class BetaTelemetry(BaseModel):
    """Empirical telemetry emitted from Container 3 (Headless Game Runtime)."""
    exit_code: int = 0
    avg_frame_time_ms: float = 0.0
    allocations_in_loop: int = 0
    tunneling_errors: int = 0
    shader_errors: int = 0
    visual_anomalies: int = 0
    headless_bot_crashes: int = 0
    raw_stdout: Optional[str] = None
    raw_stderr: Optional[str] = None


class AlphaCognitiveTrace(BaseModel):
    """Cognitive synthesis artifacts generated by Strand Alpha agents."""
    tier: TierType
    architecture_contract: Optional[str] = None
    spatial_invariants_valid: bool = True
    generated_code: Dict[str, str] = Field(default_factory=dict)
    reasoning_diagnosis: Optional[str] = None


def create_initial_state(
    codebase: Optional[Dict[str, str]] = None,
    max_cycles_per_tier: int = 5
) -> HelixState:
    """Creates a clean initial state starting at Level 1 Kernel."""
    return {
        "tier": "LEVEL_1_KERNEL",
        "codebase": codebase or {},
        "avg_frame_time_ms": 0.0,
        "allocations_in_loop": 0,
        "headless_bot_crashes": 0,
        "visual_anomalies": 0,
        "spatial_invariants_valid": False,
        "current_cycle": 0,
        "max_cycles_per_tier": max_cycles_per_tier,
    }
