"""City Echoes - Newtonian Ballistic Penetration & Spalling Subsystem.

Solves kinetic energy degradation through residential architectural assemblies:
1/2 inch gypsum drywall sheets, 2x4 spruce-pine-fir studs, and dynamic spall ejection.
"""

import math
from typing import Tuple, Optional
from doublehelix.games.city_echoes.models import (
    ProjectileSpec, MaterialPhysics, SLUG_12GAUGE, HANDGUN_9MM,
    MATERIAL_DRYWALL_SINGLE, MATERIAL_DRYWALL_DOUBLE, MATERIAL_WOOD_SPF_STUD
)


class BallisticsSimulator:
    """Computes ballistic trajectory, penetration work, and drywall spalling."""

    @staticmethod
    def calculate_penetration(
        projectile: ProjectileSpec,
        material: MaterialPhysics,
        incident_angle_deg: float = 90.0
    ) -> Tuple[bool, float, float]:
        """
        Determines whether a projectile penetrates a material barrier.
        Returns: (penetrated: bool, exit_velocity_mps: float, residual_energy_joules: float)
        """
        # 1. Ricochet evaluation
        surface_glance_angle = abs(incident_angle_deg)
        if surface_glance_angle < material.ricochet_critical_angle_deg:
            # Ricochet occurred; no penetration
            return False, projectile.muzzle_velocity_mps * 0.7, 0.0

        # 2. Oblique thickness correction
        radians = math.radians(max(5.0, surface_glance_angle))
        effective_work = material.shear_work_joules / math.sin(radians)

        initial_ke = projectile.kinetic_energy_joules
        residual_ke = initial_ke - effective_work

        if residual_ke <= 0.0:
            # Stopped by material assembly
            return False, 0.0, 0.0

        # Residual kinetic energy converted back to exit velocity: v = sqrt(2 * E / m)
        exit_velocity = math.sqrt((2.0 * residual_ke) / projectile.mass_kg)
        return True, exit_velocity, residual_ke

    @staticmethod
    def simulate_drywall_spall(
        exit_velocity: float,
        is_double_sheet: bool = True
    ) -> Tuple[int, float]:
        """
        Computes dynamic spalling generated by 12-gauge slug breach.
        Returns: (num_acoustic_chunks: int, spall_cloud_radius_meters: float)
        """
        if exit_velocity <= 0.0:
            return 0, 0.0
        # High-velocity exit ejects gypsum core chunks and paper backing
        chunk_count = 12 if is_double_sheet else 6
        cloud_radius = min(2.5, exit_velocity * 0.005)
        return chunk_count, cloud_radius
